
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ASA
 */
public class managerPage extends javax.swing.JFrame {

    /**
     * Creates new form managerPage
     * @throws FileNotFoundException 
     */
    public managerPage() throws FileNotFoundException {
        initComponents();
         
        moneyfield.setValue(c.getMoney());
        incomefield.setValue(c.getIncome());
        expancefield.setValue(c.getExpanse());
        dayfield.setValue(c.getDay());
        famefield.setValue(c.getFame());
        todayscustomerfield.setValue(c.getTodayPassengers());
        numberofstations.setValue(c.getTotalSpaceStation());
        numberofships.setValue(c.getTotalSpaceShip());
        aclassticketprice.setValue(c.getA_ShipPrice());
        bclassticketprice.setValue(c.getB_ShipPrice());
        cclassticketprice.setValue(c.getC_ShipPrice());
        
    }
    static company c = company.getInstance();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        incomefield = new javax.swing.JFormattedTextField();
        expancefield = new javax.swing.JFormattedTextField();
        moneyfield = new javax.swing.JFormattedTextField();
        backbutton = new javax.swing.JButton();
        nextdaybutton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        famefield = new javax.swing.JFormattedTextField();
        dayfield = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        numberofstations = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        numberofships = new javax.swing.JFormattedTextField();
        jLabel17 = new javax.swing.JLabel();
        todayscustomerfield = new javax.swing.JFormattedTextField();
        listplanetbox = new javax.swing.JComboBox<>();
        listshipfield = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        listshipfield1 = new javax.swing.JTextField();
        listshipfield2 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        bclassticketprice = new javax.swing.JFormattedTextField();
        cclassticketprice = new javax.swing.JFormattedTextField();
        aclassticketprice = new javax.swing.JFormattedTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        adjustbclassticketprice = new javax.swing.JFormattedTextField();
        adjustaclassticketprice = new javax.swing.JFormattedTextField();
        adjustcclassticketprice = new javax.swing.JFormattedTextField();
        applypricesbutton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        planetbox = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        shipplanetbox = new javax.swing.JComboBox<>();
        jLabel22 = new javax.swing.JLabel();
        classbox = new javax.swing.JComboBox<>();
        purchaseship = new javax.swing.JButton();
        priceofship = new javax.swing.JFormattedTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listpassengerfield = new javax.swing.JTextArea();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(900, 550));
        setMinimumSize(new java.awt.Dimension(900, 550));
        setResizable(false);

        jTabbedPane1.setBackground(new java.awt.Color(51, 51, 51));
        jTabbedPane1.setBorder(new javax.swing.border.MatteBorder(null));
        jTabbedPane1.setForeground(new java.awt.Color(204, 204, 255));
        jTabbedPane1.setFont(new java.awt.Font("Impact", 0, 12)); // NOI18N

        jPanel6.setBackground(new java.awt.Color(153, 153, 153));
        jPanel6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel1.setFont(new java.awt.Font("Unispace", 3, 18)); // NOI18N
        jLabel1.setText("Expance:");

        jLabel2.setFont(new java.awt.Font("Unispace", 3, 18)); // NOI18N
        jLabel2.setText("Income:");

        jLabel3.setFont(new java.awt.Font("Unispace", 3, 18)); // NOI18N
        jLabel3.setText("Money:");

        incomefield.setEditable(false);
        incomefield.setBackground(new java.awt.Color(51, 51, 51));
        incomefield.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        incomefield.setForeground(new java.awt.Color(255, 255, 255));
        incomefield.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getCurrencyInstance())));
        incomefield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                incomefieldActionPerformed(evt);
            }
        });

        expancefield.setEditable(false);
        expancefield.setBackground(new java.awt.Color(51, 51, 51));
        expancefield.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        expancefield.setForeground(new java.awt.Color(255, 255, 255));
        expancefield.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getCurrencyInstance())));

        moneyfield.setEditable(false);
        moneyfield.setBackground(new java.awt.Color(51, 51, 51));
        moneyfield.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        moneyfield.setForeground(new java.awt.Color(255, 255, 255));
        moneyfield.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getCurrencyInstance())));
        moneyfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moneyfieldActionPerformed(evt);
            }
        });

        backbutton.setBackground(new java.awt.Color(51, 51, 51));
        backbutton.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        backbutton.setText("Back to Main Menu");
        backbutton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        backbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbuttonActionPerformed(evt);
            }
        });

        nextdaybutton.setBackground(new java.awt.Color(51, 51, 51));
        nextdaybutton.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        nextdaybutton.setText("Next Day");
        nextdaybutton.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nextdaybuttonFocusGained(evt);
            }
        });
        nextdaybutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextdaybuttonActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Unispace", 3, 18)); // NOI18N
        jLabel4.setText("Fame:");

        famefield.setEditable(false);
        famefield.setBackground(new java.awt.Color(51, 51, 51));
        famefield.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        famefield.setForeground(new java.awt.Color(255, 255, 255));
        famefield.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        famefield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                famefieldActionPerformed(evt);
            }
        });

        dayfield.setEditable(false);
        dayfield.setBackground(new java.awt.Color(102, 102, 102));
        dayfield.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DAY", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Unispace", 3, 14))); // NOI18N
        dayfield.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("00"))));
        dayfield.setFont(new java.awt.Font("Unispace", 0, 24)); // NOI18N
        dayfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dayfieldActionPerformed(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon("spsh.png")); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon("stationp.png")); // NOI18N

        jLabel6.setFont(new java.awt.Font("Unispace", 1, 14)); // NOI18N
        jLabel6.setText("Space Ships:");

        numberofstations.setEditable(false);
        numberofstations.setBackground(new java.awt.Color(102, 102, 102));
        numberofstations.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        numberofstations.setFont(new java.awt.Font("Unispace", 1, 14)); // NOI18N
        numberofstations.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberofstationsActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Unispace", 1, 14)); // NOI18N
        jLabel8.setText("Space Stations:");

        numberofships.setEditable(false);
        numberofships.setBackground(new java.awt.Color(102, 102, 102));
        numberofships.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        numberofships.setFont(new java.awt.Font("Unispace", 1, 14)); // NOI18N

        jLabel17.setFont(new java.awt.Font("Unispace", 3, 14)); // NOI18N
        jLabel17.setText("Today's Customers");

        todayscustomerfield.setEditable(false);
        todayscustomerfield.setBackground(new java.awt.Color(51, 51, 51));
        todayscustomerfield.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        todayscustomerfield.setForeground(new java.awt.Color(255, 255, 255));
        todayscustomerfield.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        todayscustomerfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                todayscustomerfieldActionPerformed(evt);
            }
        });

        listplanetbox.setBackground(new java.awt.Color(102, 102, 102));
        listplanetbox.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        listplanetbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Zerthor" }));
        listplanetbox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                listplanetboxİtemStateChanged(evt);
            }
        });
        listplanetbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listplanetboxActionPerformed(evt);
            }
        });

        listshipfield.setEditable(false);
        listshipfield.setBackground(new java.awt.Color(102, 102, 102));
        listshipfield.setFont(new java.awt.Font("Unispace", 3, 12)); // NOI18N

        jButton2.setBackground(new java.awt.Color(51, 51, 51));
        jButton2.setFont(new java.awt.Font("Unispace", 0, 14)); // NOI18N
        jButton2.setText("List");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        listshipfield1.setEditable(false);
        listshipfield1.setBackground(new java.awt.Color(102, 102, 102));
        listshipfield1.setFont(new java.awt.Font("Unispace", 3, 12)); // NOI18N

        listshipfield2.setEditable(false);
        listshipfield2.setBackground(new java.awt.Color(102, 102, 102));
        listshipfield2.setFont(new java.awt.Font("Unispace", 3, 12)); // NOI18N

        jLabel23.setBackground(new java.awt.Color(153, 153, 153));
        jLabel23.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        jLabel23.setText("List space ships:");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(nextdaybutton, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addGap(27, 27, 27)
                                        .addComponent(backbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel6Layout.createSequentialGroup()
                                                .addGap(43, 43, 43)
                                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel1)
                                                    .addComponent(jLabel3)
                                                    .addComponent(jLabel2)
                                                    .addComponent(jLabel4)))
                                            .addGroup(jPanel6Layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(incomefield, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(famefield, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(moneyfield, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(expancefield, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(todayscustomerfield, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(68, 68, 68)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel6Layout.createSequentialGroup()
                                            .addComponent(jLabel8)
                                            .addGap(18, 18, 18)
                                            .addComponent(numberofstations, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jButton2))))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel23)
                                .addGap(18, 18, 18)
                                .addComponent(listplanetbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)))
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(numberofships, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(listshipfield1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(listshipfield2, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(listshipfield, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(dayfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(jLabel2))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(incomefield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(expancefield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 14, Short.MAX_VALUE)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(moneyfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(famefield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(todayscustomerfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17))
                        .addGap(108, 108, 108)
                        .addComponent(dayfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(112, 112, 112))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(numberofstations, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(numberofships, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(listshipfield, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(listplanetbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel23)))
                        .addGap(18, 18, 18)
                        .addComponent(listshipfield1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton2)
                            .addComponent(listshipfield2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(111, 111, 111)))
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nextdaybutton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Company", jPanel6);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        jLabel10.setIcon(new javax.swing.ImageIcon("shipa.png")); // NOI18N

        jLabel11.setIcon(new javax.swing.ImageIcon("shipb.png")); // NOI18N

        jLabel12.setIcon(new javax.swing.ImageIcon("shipc.png")); // NOI18N

        jLabel9.setBackground(new java.awt.Color(51, 51, 51));
        jLabel9.setFont(new java.awt.Font("Unispace", 3, 14)); // NOI18N
        jLabel9.setText("B Class Ship");

        jLabel13.setBackground(new java.awt.Color(51, 51, 51));
        jLabel13.setFont(new java.awt.Font("Unispace", 3, 14)); // NOI18N
        jLabel13.setText("A Class Ship");

        jLabel14.setBackground(new java.awt.Color(51, 51, 51));
        jLabel14.setFont(new java.awt.Font("Unispace", 3, 14)); // NOI18N
        jLabel14.setText("C Class Ship");

        bclassticketprice.setEditable(false);
        bclassticketprice.setBackground(new java.awt.Color(51, 51, 51));
        bclassticketprice.setForeground(new java.awt.Color(255, 255, 255));
        bclassticketprice.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getCurrencyInstance())));
        bclassticketprice.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        cclassticketprice.setEditable(false);
        cclassticketprice.setBackground(new java.awt.Color(51, 51, 51));
        cclassticketprice.setForeground(new java.awt.Color(255, 255, 255));
        cclassticketprice.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getCurrencyInstance())));
        cclassticketprice.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        aclassticketprice.setEditable(false);
        aclassticketprice.setBackground(new java.awt.Color(51, 51, 51));
        aclassticketprice.setForeground(new java.awt.Color(255, 255, 255));
        aclassticketprice.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getCurrencyInstance())));
        aclassticketprice.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jLabel15.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        jLabel15.setText("Ticket Prices:");

        jLabel16.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        jLabel16.setText("Adjust Prices:");

        adjustbclassticketprice.setBackground(new java.awt.Color(51, 51, 51));
        adjustbclassticketprice.setForeground(new java.awt.Color(204, 204, 204));
        adjustbclassticketprice.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        adjustbclassticketprice.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        adjustbclassticketprice.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                adjustbclassticketpriceFocusGained(evt);
            }
        });

        adjustaclassticketprice.setBackground(new java.awt.Color(51, 51, 51));
        adjustaclassticketprice.setForeground(new java.awt.Color(204, 204, 204));
        adjustaclassticketprice.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        adjustaclassticketprice.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        adjustaclassticketprice.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                adjustaclassticketpriceFocusGained(evt);
            }
        });

        adjustcclassticketprice.setBackground(new java.awt.Color(51, 51, 51));
        adjustcclassticketprice.setForeground(new java.awt.Color(204, 204, 204));
        adjustcclassticketprice.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        adjustcclassticketprice.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        adjustcclassticketprice.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                adjustcclassticketpriceFocusGained(evt);
            }
        });

        applypricesbutton.setBackground(new java.awt.Color(51, 51, 51));
        applypricesbutton.setFont(new java.awt.Font("Unispace", 0, 14)); // NOI18N
        applypricesbutton.setText("Apply New Prices");
        applypricesbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                applypricesbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aclassticketprice, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bclassticketprice, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adjustbclassticketprice, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(160, 160, 160)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cclassticketprice, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(89, 89, 89))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(applypricesbutton)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(49, 49, 49)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(47, 47, 47)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(47, 47, 47)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel16)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(adjustaclassticketprice, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(adjustcclassticketprice, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(28, 28, 28))))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aclassticketprice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bclassticketprice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cclassticketprice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(72, 72, 72)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adjustaclassticketprice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adjustbclassticketprice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adjustcclassticketprice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addComponent(applypricesbutton)
                .addGap(21, 21, 21))
        );

        jTabbedPane1.addTab("Adjust price of the tickets", jPanel1);

        jTabbedPane2.setFont(new java.awt.Font("Calibri Light", 1, 12)); // NOI18N

        jPanel4.setBackground(new java.awt.Color(153, 153, 153));

        jLabel18.setIcon(new javax.swing.ImageIcon("emptystation.png")); // NOI18N

        planetbox.setBackground(new java.awt.Color(102, 102, 102));
        planetbox.setFont(new java.awt.Font("Unispace", 0, 14)); // NOI18N
        planetbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Xandar", "Valtor", "Ophiria", "Quorin", "Nyxus", "Luxoria", "Krynn", "Pyraxis", "Avarus", "Vesperia", "Aethon", "Thalassia", "Tenebris", "Arcturus", "Helios", "Draconis", "Nihlus", "Eridani", "Novaria" }));

        jLabel19.setFont(new java.awt.Font("Unispace", 0, 14)); // NOI18N
        jLabel19.setText("Select a Planet:");

        jFormattedTextField1.setEditable(false);
        jFormattedTextField1.setBackground(new java.awt.Color(102, 102, 102));
        jFormattedTextField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getCurrencyInstance())));
        jFormattedTextField1.setText("₺10.000,00");
        jFormattedTextField1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(102, 102, 102));
        jTextField1.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        jTextField1.setText("3 park place");

        jButton1.setBackground(new java.awt.Color(51, 51, 51));
        jButton1.setFont(new java.awt.Font("Unispace", 0, 18)); // NOI18N
        jButton1.setText("PURCHASE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addComponent(jLabel19)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(planetbox, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(271, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(393, 393, 393))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(planetbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addComponent(jButton1)
                .addContainerGap(73, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Buy Space Stations", jPanel4);

        jPanel5.setBackground(new java.awt.Color(153, 153, 153));

        jLabel20.setIcon(new javax.swing.ImageIcon("shipc.png")); // NOI18N

        jLabel21.setFont(new java.awt.Font("Unispace", 0, 14)); // NOI18N
        jLabel21.setText("Select a Planet:");

        shipplanetbox.setBackground(new java.awt.Color(102, 102, 102));
        shipplanetbox.setFont(new java.awt.Font("Unispace", 0, 14)); // NOI18N
        shipplanetbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Zerthor" }));

        jLabel22.setFont(new java.awt.Font("Unispace", 0, 14)); // NOI18N
        jLabel22.setText("Select a Class:");

        classbox.setBackground(new java.awt.Color(102, 102, 102));
        classbox.setFont(new java.awt.Font("Unispace", 0, 14)); // NOI18N
        classbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "C" }));
        classbox.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                classboxFocusGained(evt);
            }
        });
        classbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                classboxActionPerformed(evt);
            }
        });

        purchaseship.setBackground(new java.awt.Color(51, 51, 51));
        purchaseship.setFont(new java.awt.Font("Unispace", 0, 18)); // NOI18N
        purchaseship.setText("PURCHASE");
        purchaseship.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                purchaseshipActionPerformed(evt);
            }
        });

        priceofship.setEditable(false);
        priceofship.setBackground(new java.awt.Color(102, 102, 102));
        priceofship.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getCurrencyInstance())));
        priceofship.setText("₺4.000,00");
        priceofship.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(316, 316, 316)
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(jLabel21)
                        .addGap(18, 18, 18)
                        .addComponent(shipplanetbox, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(classbox, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(411, 411, 411)
                        .addComponent(priceofship, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(390, 390, 390)
                        .addComponent(purchaseship)))
                .addContainerGap(197, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(80, 80, 80)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(shipplanetbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(classbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(priceofship, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(purchaseship)
                .addGap(73, 73, 73))
        );

        jTabbedPane2.addTab("Buy Space Ships", jPanel5);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );

        jTabbedPane1.addTab("Purchase", jPanel2);

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));

        listpassengerfield.setEditable(false);
        listpassengerfield.setBackground(new java.awt.Color(153, 153, 153));
        listpassengerfield.setColumns(20);
        listpassengerfield.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        listpassengerfield.setRows(5);
        listpassengerfield.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "List The Passengers", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Unispace", 0, 10))); // NOI18N
        jScrollPane1.setViewportView(listpassengerfield);

        jButton3.setBackground(new java.awt.Color(51, 51, 51));
        jButton3.setFont(new java.awt.Font("Unispace", 0, 18)); // NOI18N
        jButton3.setText("LIST");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(116, 116, 116)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(109, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(201, 201, 201)
                        .addComponent(jButton3)))
                .addContainerGap(133, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("List customers", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void incomefieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_incomefieldActionPerformed
        // TODO add your handling code here:
       
        
    }//GEN-LAST:event_incomefieldActionPerformed

    private void moneyfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moneyfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_moneyfieldActionPerformed

    private void backbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbuttonActionPerformed
        // TODO add your handling code here:
        dispose();
        loginmenu l = new loginmenu();
        l.setVisible(true);
    }//GEN-LAST:event_backbuttonActionPerformed

    
    private void nextdaybuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextdaybuttonActionPerformed
        try {
            // TODO add your handling code here:
            c.dayCycle();
            flag1 = false;
            moneyfield.setValue(c.getMoney());
            incomefield.setValue(c.getIncome());
            expancefield.setValue(c.getExpanse());
            dayfield.setValue(c.getDay());
            famefield.setValue(c.getFame());
            todayscustomerfield.setValue(c.getTodayPassengers());
            setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(managerPage.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        
    }//GEN-LAST:event_nextdaybuttonActionPerformed

    private void famefieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_famefieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_famefieldActionPerformed

    private void dayfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dayfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dayfieldActionPerformed

    private void nextdaybuttonFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nextdaybuttonFocusGained
        // TODO add your handling code here:
        
    }//GEN-LAST:event_nextdaybuttonFocusGained

    private void applypricesbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_applypricesbuttonActionPerformed
        // TODO add your handling code here:
        
        if (adjustaclassticketprice.getValue() != null) {
            c.setA_ShipPrice((long) adjustaclassticketprice.getValue());
            aclassticketprice.setValue(c.getA_ShipPrice());
        }
        if (adjustbclassticketprice.getValue() != null) {
            c.setB_ShipPrice((long) adjustbclassticketprice.getValue());
            bclassticketprice.setValue(c.getB_ShipPrice());
        }
        if (adjustcclassticketprice.getValue() != null) {
            c.setC_ShipPrice((long) adjustcclassticketprice.getValue());
            cclassticketprice.setValue(c.getC_ShipPrice());
        }
        
        
        
    }//GEN-LAST:event_applypricesbuttonActionPerformed

    private void numberofstationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberofstationsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numberofstationsActionPerformed

    private void adjustaclassticketpriceFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_adjustaclassticketpriceFocusGained
        // TODO add your handling code here:
        adjustaclassticketprice.setValue(null);
    }//GEN-LAST:event_adjustaclassticketpriceFocusGained

    private void adjustbclassticketpriceFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_adjustbclassticketpriceFocusGained
        // TODO add your handling code here:
        adjustbclassticketprice.setValue(null);
    }//GEN-LAST:event_adjustbclassticketpriceFocusGained

    private void adjustcclassticketpriceFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_adjustcclassticketpriceFocusGained
        // TODO add your handling code here:
        adjustcclassticketprice.setValue(null);
    }//GEN-LAST:event_adjustcclassticketpriceFocusGained

    private void todayscustomerfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_todayscustomerfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_todayscustomerfieldActionPerformed

    private void listplanetboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listplanetboxActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_listplanetboxActionPerformed

    private void listplanetboxİtemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_listplanetboxİtemStateChanged
        // TODO add your handling code here:
       
    }//GEN-LAST:event_listplanetboxİtemStateChanged
    
    
    
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String planet = planetbox.getItemAt(planetbox.getSelectedIndex());
        
        
        if (c.getMoney() >= 10000) {
            c.purchaseSpaceStation(planet);
            numberofstations.setValue(c.getTotalSpaceStation());
            shipplanetbox.addItem(planet);
            listplanetbox.addItem(planet);
            if (planetbox.getItemCount() != 0) {
                planetbox.removeItemAt(planetbox.getSelectedIndex());
            }
            
            moneyfield.setValue(c.getMoney());
            incomefield.setValue(c.getIncome());
            expancefield.setValue(c.getExpanse());
            JOptionPane.showMessageDialog(this, "The space station has been purchased!", "Succes", JOptionPane.INFORMATION_MESSAGE);
        }
        else{
            JOptionPane.showMessageDialog(this, "The company does not have enough money", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    
    public static ArrayList<String> dictionary = new ArrayList<>();
    
    private void purchaseshipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_purchaseshipActionPerformed
        // TODO add your handling code here:
        String planet = shipplanetbox.getItemAt(shipplanetbox.getSelectedIndex());
        String classtype = classbox.getItemAt(classbox.getSelectedIndex());
        Stack s = c.getSpaceShip(planet);
        if (classtype.equals("A") && c.getMoney() >= 4000) {
            if (s.size()< 3) {
                c.purchaseSpaceShip(planet, classtype);
                dictionary.add(planet + ","+ "A");
                JOptionPane.showMessageDialog(this, "A class space ship has been purchased!", "Success", JOptionPane.INFORMATION_MESSAGE);
            }
            else{
                JOptionPane.showMessageDialog(this, "All stations are full in selected planet. You must purchase new station.", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        }
        else if (classtype.equals("B") && c.getMoney() >= 2000) {
            if (s.size()< 3) {
                c.purchaseSpaceShip(planet, classtype);
                dictionary.add(planet + ","+ "B");
                JOptionPane.showMessageDialog(this, "B class space ship has been purchased!", "Success", JOptionPane.INFORMATION_MESSAGE);
            }
            else{
                JOptionPane.showMessageDialog(this, "All stations are full in selected planet. You must purchase new station. ", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        }
        else if (classtype.equals("C") && c.getMoney() >= 1000) {
            if (s.size()< 3) {
                c.purchaseSpaceShip(planet, classtype);
                dictionary.add(planet + ","+ "C");
                JOptionPane.showMessageDialog(this, "C class space ship has been purchased!", "Success", JOptionPane.INFORMATION_MESSAGE);
            }
            else{
                JOptionPane.showMessageDialog(this, "All stations are full in selected planet. You must purchase new station.", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        }
        else{
            JOptionPane.showMessageDialog(this, "The company does not have enough money", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
        numberofships.setValue(c.getTotalSpaceShip());
        moneyfield.setValue(c.getMoney());
        incomefield.setValue(c.getIncome());
        expancefield.setValue(c.getExpanse());
        
    }//GEN-LAST:event_purchaseshipActionPerformed

    
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String planet = listplanetbox.getItemAt(listplanetbox.getSelectedIndex());
        Stack temp = c.getSpaceShip(planet);
        listshipfield.setText("");
        listshipfield1.setText("");
        listshipfield2.setText("");
        if (temp.size() == 3) {
            listshipfield.setText("Class Type: "+((Ships) temp.pop()).getShipType());
            listshipfield1.setText("Class Type: "+((Ships) temp.pop()).getShipType());
            listshipfield2.setText("Class Type: "+((Ships) temp.pop()).getShipType());
        }
        else if (temp.size() == 2) {
            listshipfield.setText("Class Type: "+((Ships) temp.pop()).getShipType());
            listshipfield1.setText("Class Type: "+((Ships) temp.pop()).getShipType());
        }
        else if (temp.size() == 1) {
            listshipfield.setText("Class Type: "+((Ships) temp.pop()).getShipType());
            
        }
    }//GEN-LAST:event_jButton2ActionPerformed
    boolean flag1=passengerPage.isticketbought;
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String[] list = c.getlistpassenger();
        StringBuilder sb = new StringBuilder();
        for (int i = 0; i < list.length; i++) {
            sb.append(list[i]).append("\n");
        }
        
        if (flag1) {
            sb.append(passengerPage.name + ", " +passengerPage.lastname + ", " + passengerPage.gender+ ", " + passengerPage.age);
        }
        listpassengerfield.setText(sb.toString());
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void classboxFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_classboxFocusGained
        // TODO add your handling code here:
        
    }//GEN-LAST:event_classboxFocusGained

    private void classboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_classboxActionPerformed
        // TODO add your handling code here:
        if (classbox.getItemAt(classbox.getSelectedIndex()).equals("A")) {
            priceofship.setValue(4000);
        }
        if (classbox.getItemAt(classbox.getSelectedIndex()).equals("B")) {
            priceofship.setValue(2000);
        }
        if (classbox.getItemAt(classbox.getSelectedIndex()).equals("C")) {
            priceofship.setValue(1000);
        }
    }//GEN-LAST:event_classboxActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(managerPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(managerPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(managerPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(managerPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
					new managerPage().setVisible(true);
				} catch (FileNotFoundException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
            }
        });
        
    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField aclassticketprice;
    private javax.swing.JFormattedTextField adjustaclassticketprice;
    private javax.swing.JFormattedTextField adjustbclassticketprice;
    private javax.swing.JFormattedTextField adjustcclassticketprice;
    private javax.swing.JButton applypricesbutton;
    private javax.swing.JButton backbutton;
    private javax.swing.JFormattedTextField bclassticketprice;
    private javax.swing.JFormattedTextField cclassticketprice;
    private javax.swing.JComboBox<String> classbox;
    private javax.swing.JFormattedTextField dayfield;
    private javax.swing.JFormattedTextField expancefield;
    private javax.swing.JFormattedTextField famefield;
    private javax.swing.JFormattedTextField incomefield;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextArea listpassengerfield;
    private javax.swing.JComboBox<String> listplanetbox;
    private javax.swing.JTextField listshipfield;
    private javax.swing.JTextField listshipfield1;
    private javax.swing.JTextField listshipfield2;
    private javax.swing.JFormattedTextField moneyfield;
    private javax.swing.JButton nextdaybutton;
    private javax.swing.JFormattedTextField numberofships;
    private javax.swing.JFormattedTextField numberofstations;
    private javax.swing.JComboBox<String> planetbox;
    private javax.swing.JFormattedTextField priceofship;
    private javax.swing.JButton purchaseship;
    private javax.swing.JComboBox<String> shipplanetbox;
    private javax.swing.JFormattedTextField todayscustomerfield;
    // End of variables declaration//GEN-END:variables
}
