
import java.io.FileNotFoundException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ASA
 */
public class passengerPage extends javax.swing.JFrame {

    /**
     * Creates new form passengerPage
     */
    public passengerPage() throws FileNotFoundException {
        initComponents();
        
        
        String username = loginmenu.name2;
        String password = loginmenu.pass2;
        
        String[][] users = k.fileop("users.txt");
       
        for (int i = 0; i < users.length; i++) {
            if (users[i][0].equals(username) && users[i][1].equals(password) && users[i][2].equals("C")) {
                
                name = users[i][3];
                lastname = users[i][4];
                gender = users[i][5];
                age = users[i][6];
            }
        }
        dict = m.dictionary;
        cusnamefield.setText(name);
        cuslastnamefield.setText(lastname);
        cusgenderfield.setText(gender);
        cusagefield.setText(age);
        dict.add("Zerthor"+ "," + "C");
        
        planets = stringArrayToTwoDimensionalArray(dict);
        for (int i = 0; i < planets.length; i++) {
            selectplanetbox.addItem(planets[i][0]);
        }
        
    }
    loginmenu k =new loginmenu();
    managerPage m = new managerPage();
    ArrayList<String> dict = new ArrayList<>();
    String[][] planets;
    static String name = null;
    static String lastname = null;
    static String gender = null;
    static String age = null;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cuslastnamefield = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cusnamefield = new javax.swing.JTextField();
        cusgenderfield = new javax.swing.JTextField();
        cusagefield = new javax.swing.JTextField();
        selectplanetbox = new javax.swing.JComboBox<>();
        selectedclassbox = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        priceofticket = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        buybutton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(900, 550));
        setMinimumSize(new java.awt.Dimension(900, 550));
        setPreferredSize(new java.awt.Dimension(900, 550));

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Unispace", 0, 14)); // NOI18N
        jLabel1.setText("NAME:");

        jLabel2.setFont(new java.awt.Font("Unispace", 0, 14)); // NOI18N
        jLabel2.setText("LASTNAME:");

        cuslastnamefield.setEditable(false);
        cuslastnamefield.setBackground(new java.awt.Color(102, 102, 102));
        cuslastnamefield.setFont(new java.awt.Font("Unispace", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Unispace", 0, 14)); // NOI18N
        jLabel3.setText("GENDER:");

        jLabel4.setFont(new java.awt.Font("Unispace", 0, 14)); // NOI18N
        jLabel4.setText("AGE:");

        jLabel5.setBackground(new java.awt.Color(102, 102, 102));
        jLabel5.setFont(new java.awt.Font("Unispace", 0, 22)); // NOI18N
        jLabel5.setText("PASSENGER INFORMATIONS:");

        cusnamefield.setEditable(false);
        cusnamefield.setBackground(new java.awt.Color(102, 102, 102));
        cusnamefield.setFont(new java.awt.Font("Unispace", 0, 14)); // NOI18N

        cusgenderfield.setEditable(false);
        cusgenderfield.setBackground(new java.awt.Color(102, 102, 102));
        cusgenderfield.setFont(new java.awt.Font("Unispace", 0, 14)); // NOI18N

        cusagefield.setEditable(false);
        cusagefield.setBackground(new java.awt.Color(102, 102, 102));
        cusagefield.setFont(new java.awt.Font("Unispace", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cusnamefield, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cuslastnamefield, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cusgenderfield, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cusagefield, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cusnamefield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cuslastnamefield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cusgenderfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cusagefield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(277, Short.MAX_VALUE))
        );

        selectplanetbox.setBackground(new java.awt.Color(102, 102, 102));
        selectplanetbox.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        selectplanetbox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                selectplanetboxİtemStateChanged(evt);
            }
        });
        selectplanetbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectplanetboxActionPerformed(evt);
            }
        });

        selectedclassbox.setBackground(new java.awt.Color(102, 102, 102));
        selectedclassbox.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        selectedclassbox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                selectedclassboxİtemStateChanged(evt);
            }
        });
        selectedclassbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectedclassboxActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(51, 51, 51));
        jButton1.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        jButton1.setText("Back To Main Menu");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        jLabel6.setText("Please select the planet you want to go to:");

        jLabel7.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        jLabel7.setText("Select the class of the ship you want to travel by:");

        priceofticket.setEditable(false);
        priceofticket.setBackground(new java.awt.Color(102, 102, 102));
        priceofticket.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getCurrencyInstance())));
        priceofticket.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        jLabel8.setText("Price of the ticket:");

        buybutton.setBackground(new java.awt.Color(51, 51, 51));
        buybutton.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        buybutton.setText("Buy the ticket");
        buybutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buybuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(selectplanetbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(selectedclassbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 173, Short.MAX_VALUE)
                                .addComponent(buybutton))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(priceofticket, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(selectplanetbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(selectedclassbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(priceofticket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(buybutton))
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public String[][] stringArrayToTwoDimensionalArray(ArrayList<String> a) {
    String[] arr = convertToArray(dict);
// Planetleri ve elemanları saklamak için bir HashMap kullanalım
    HashMap<String, ArrayList<String>> planetMap = new HashMap<>();

    // Tek boyutlu diziyi döngü ile tarayalım
    for (String element : arr) {
        // Elemanı virgüllerden ayıralım
        String[] parts = element.split(",");

        // Planet ve elemanı alalım
        String planet = parts[0].trim();
        String item = parts[1].trim();

        // Eğer planet daha önce eklenmemişse, yeni bir giriş oluşturalım
        if (!planetMap.containsKey(planet)) {
            planetMap.put(planet, new ArrayList<>());
        }

        // Elemanı planetin değerlerine ekleyelim
        planetMap.get(planet).add(item);
    }

    // İki boyutlu sonucu oluşturalım
    String[][] result = new String[planetMap.size()][];
    int i = 0;

    // Her bir planet için sütunları oluşturalım
    for (Map.Entry<String, ArrayList<String>> entry : planetMap.entrySet()) {
        String planet = entry.getKey();
        ArrayList<String> items = entry.getValue();

        // Planetin sütununu ve elemanları iki boyutlu sonuca ekle
        result[i] = new String[items.size() + 1];
        result[i][0] = planet;

        for (int j = 0; j < items.size(); j++) {
            result[i][j + 1] = items.get(j);
        }

        i++;
    }

    return result;
}
    public static String[] convertToArray(ArrayList<String> arrayList) {
        String[] array = new String[arrayList.size()]; // ArrayList'in boyutu kadar bir dizi oluşturuluyor
        
        for (int i = 0; i < arrayList.size(); i++) {
            array[i] = arrayList.get(i); // ArrayList'teki elemanlar diziye atanıyor
        }
        
        return array; // Dizi döndürülüyor
    }
    
    private void selectplanetboxİtemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_selectplanetboxİtemStateChanged
        // TODO add your handling code here:

    }//GEN-LAST:event_selectplanetboxİtemStateChanged

    private void selectplanetboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectplanetboxActionPerformed
        
        selectedclassbox.removeAllItems();
        for (int i = 0; i < planets.length; i++) {
            for (int j = 1; j < planets[i].length; j++) {
                if(selectplanetbox.getItemAt(selectplanetbox.getSelectedIndex()).equals(planets[i][0])){
                    selectedclassbox.addItem(planets[i][j]);
                }
            }
        }

    }//GEN-LAST:event_selectplanetboxActionPerformed

    private void selectedclassboxİtemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_selectedclassboxİtemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_selectedclassboxİtemStateChanged

    private void selectedclassboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectedclassboxActionPerformed
        // TODO add your handling code here:
        if (selectedclassbox.getItemAt(selectedclassbox.getSelectedIndex()).equals("A")) {
            priceofticket.setValue(m.c.getA_ShipPrice());
        }
        if (selectedclassbox.getItemAt(selectedclassbox.getSelectedIndex()).equals("B")) {
            priceofticket.setValue(m.c.getB_ShipPrice());
        }
        if (selectedclassbox.getItemAt(selectedclassbox.getSelectedIndex()).equals("C")) {
            priceofticket.setValue(m.c.getC_ShipPrice());
        }
        
    }//GEN-LAST:event_selectedclassboxActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
        loginmenu l = new loginmenu();//back to main menu 
        l.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    static boolean isticketbought;
    private void buybuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buybuttonActionPerformed
        // TODO add your handling code here:
        isticketbought = true;
        JOptionPane.showMessageDialog(this, "Ticket purchased. Spacex Transport wishes you a good travel.", "Success", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_buybuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(passengerPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(passengerPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(passengerPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(passengerPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new passengerPage().setVisible(true);
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(passengerPage.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buybutton;
    private javax.swing.JTextField cusagefield;
    private javax.swing.JTextField cusgenderfield;
    private javax.swing.JTextField cuslastnamefield;
    private javax.swing.JTextField cusnamefield;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JFormattedTextField priceofticket;
    private javax.swing.JComboBox<String> selectedclassbox;
    private javax.swing.JComboBox<String> selectplanetbox;
    // End of variables declaration//GEN-END:variables
}
